test

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -7,11 +7,10 @@ jobs:
       fail-fast: false
       matrix:
         virtual-environment: [ubuntu-20.04]
-        file: [".git", "node_modules/ajv/lib/dotjs/README.md", "node_modules/ajv/README.md", "node_modules/dashdash/README.md", "node_modules/fast-json-stable-stringify/README.md", "node_modules/form-data/README.md", "node_modules/isstream/README.md", "node_modules/json-schema/README.md", "node_modules/jsprim/README.md", "node_modules/mime-types/README.md", "node_modules/performance-now/README.md", "node_modules/qs/README.md", "node_modules/safe-buffer/README.md", "node_modules/sshpk/README.md", "node_modules/tough-cookie/README.md", "node_modules/tweetnacl/README.md", "node_modules/uuid/README.md", "node_modules/verror/README.md"]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - # Expecting: build ok
+      - # Expecting: build ok""
         # Actual behavior: build ok
         name: Build container(s) in docker-compose.works.yml
         run: docker-compose -f docker-compose.works.yml --verbose build
@@ -20,7 +19,93 @@ jobs:
         name: Build container(s) in docker-compose.fails.yml
         #run: docker-compose -f docker-compose.fails.yml build
         run: |
-          rm -rf ${{ matrix.file }}
+          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
+          echo "${output}"
+          if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
+            exit 1
+          fi
+      - # Expecting: build ok
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml --verbose build
+  test2:
+    runs-on: ${{ matrix.virtual-environment }}
+    strategy:
+      fail-fast: false
+      matrix:
+        virtual-environment: [ubuntu-20.04]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - # Expecting: build ok""
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml --verbose build
+      - # Expecting: 'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
+        name: Build container(s) in docker-compose.fails.yml
+        #run: docker-compose -f docker-compose.fails.yml build
+        run: |
+          rm -rf .git
+          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
+          echo "${output}"
+          if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
+            exit 1
+          fi
+      - # Expecting: build ok
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml --verbose build
+  test3:
+    runs-on: ${{ matrix.virtual-environment }}
+    strategy:
+      fail-fast: false
+      matrix:
+        virtual-environment: [ubuntu-20.04]
+        file: ["ajv", "dashdash", "fast-json-stable-stringify", "form-data", "isstream", "json-schema", "jsprim", "mime-types", "performance-now", "qs", "safe-buffer", "sshpk", "tough-cookie", "tweetnacl", "uuid", "verror"]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - # Expecting: build ok""
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml --verbose build
+      - # Expecting: 'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
+        name: Build container(s) in docker-compose.fails.yml
+        #run: docker-compose -f docker-compose.fails.yml build
+        run: |
+          find node_modules -mindepth 1 -maxdepth 1 -type d ! -name ${{ matrix.file }} -exec rm -rf {} \;
+          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
+          echo "${output}"
+          if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
+            exit 1
+          fi
+      - # Expecting: build ok
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml --verbose build
+  test4:
+    runs-on: ${{ matrix.virtual-environment }}
+    strategy:
+      fail-fast: false
+      matrix:
+        virtual-environment: [ubuntu-20.04]
+        file: ["ajv", "dashdash", "fast-json-stable-stringify", "form-data", "isstream", "json-schema", "jsprim", "mime-types", "performance-now", "qs", "safe-buffer", "sshpk", "tough-cookie", "tweetnacl", "uuid", "verror"]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - # Expecting: build ok""
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml --verbose build
+      - # Expecting: 'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
+        name: Build container(s) in docker-compose.fails.yml
+        #run: docker-compose -f docker-compose.fails.yml build
+        run: |
+          rm -rf .git
+          find node_modules -mindepth 1 -maxdepth 1 -type d ! -name ${{ matrix.file }} -exec rm -rf {} \;
           output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
           echo "${output}"
           if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
