next try

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -42,14 +42,30 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
+      - name: env
+        run: env
       - name: Install npm package(s)
         run: npm install ${{ matrix.node-package }}
       - name: Uninstall npm package(s)
         run: npm uninstall ${{ matrix.node-package }}
+      - name: env
+        run: env
       - # Expecting: build ok
         # Actual behavior: build ok
         name: Build container(s) in docker-compose.works.yml
         run: docker-compose -f docker-compose.works.yml build
+      - # Expecting: 'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
+        name: Build container(s) in docker-compose.fails.yml
+        #run: docker-compose -f docker-compose.fails.yml build
+        run: |
+          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
+          echo "${output}"
+          if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
+            exit 1
+          fi
+      - name: Remove node_modules folder
+        run: rm node_modules
       - # Expecting: 'invalid reference format: repository name must be lowercase'
         # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
         name: Build container(s) in docker-compose.fails.yml
